name: reverse_proxy
description: Example showcasing reverse proxy capabilities of Jaguar.
version: 0.0.1
homepage: https://github.com/jaguar-examples/reverse_proxy
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^0.6.1
  jaguar_dev_proxy: ^0.0.5
  http: any
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

dev_dependencies:
  test: ^0.12.0

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
